version: '3'

# docker-compose.yml example for https://github.com/ServerContainers/samba

services:
  samba:
    build: .
    image: ghcr.io/servercontainers/samba
    container_name: samba
    restart: always
    network_mode: host
    # uncomment to solve bug: https://github.com/ServerContainers/samba/issues/50 - wsdd2 only - not needed for samba
    cap_add:
     - CAP_NET_ADMIN
    environment:
      MODEL: 'TimeCapsule'
      AVAHI_NAME: StorageServer

      SAMBA_CONF_LOG_LEVEL: 3

      # uncomment to disable optional services
      #WSDD2_DISABLE: 1
      #AVAHI_DISABLE: 1

      "GROUP_${SHARES_GROUP_NAME}": ${SHARES_GROUP_ID}
      # GROUP_family: 1500

      "ACCOUNT_${USER_1_NAME}": ${USER_1_PASS}
      "UID_${USER_1_NAME}": ${USER_1_ID}
      "GROUPS_${USER_1_NAME}": ${SHARES_GROUP_NAME}

      "ACCOUNT_${USER_2_NAME}": ${USER_2_PASS}
      "UID_${USER_2_NAME}": ${USER_2_ID}
      "GROUPS_${USER_2_NAME}": ${SHARES_GROUP_NAME}

      # SAMBA_VOLUME_CONFIG_shared_home: "[Home]; path=/shares/homes/%U; valid users = alice, bob, foo; guest ok = no; read only = no; browseable = yes"

      "SAMBA_VOLUME_CONFIG_${USER_1_NAME}": "[${USER_1_SHARE_NAME}]; path=/shares/${USER_1_SHARE_NAME}; valid users = ${USER_1_NAME}; guest ok = no; read only = no; browseable = yes"
      # SAMBA_VOLUME_CONFIG_aliceonly: "[Alice Share]; path=/shares/alice; valid users = alice; guest ok = no; read only = no; browseable = yes"
      # SAMBA_VOLUME_CONFIG_alicehidden: "[Alice Hidden Share]; path=/shares/alice-hidden; valid users = alice; guest ok = no; read only = no; browseable = no"

      "SAMBA_VOLUME_CONFIG_${USER_2_NAME}": "[${USER_2_SHARE_NAME}]; path=/shares/${USER_2_SHARE_NAME}; valid users = ${USER_2_NAME}; guest ok = no; read only = no; browseable = yes"
      # SAMBA_VOLUME_CONFIG_bobonly: "[Bob Share]; path=/shares/bob; valid users = bob; guest ok = no; read only = no; browseable = yes"

      "SAMBA_VOLUME_CONFIG_${SHARED_NAME}": "[${SHARED_NAME}]; path=/shares/${SHARED_NAME}; guest ok = yes; read only = no; browseable = yes; force group = family"
      # SAMBA_VOLUME_CONFIG_public: "[Public]; path=/shares/public; valid users = alice, bob, foo; guest ok = no; read only = no; browseable = yes; force group = family"
      # SAMBA_VOLUME_CONFIG_public_ro: "[Public ReadOnly]; path=/shares/public; guest ok = yes; read only = yes; browseable = yes; force group = family"

      # SAMBA_VOLUME_CONFIG_timemachine: "[TimeMachine]; path=/shares/timemachine/%U; valid users = alice, bob, foo; guest ok = no; read only = no; browseable = yes; fruit:time machine = yes; fruit:time machine max size = 500G"
    volumes:
      # - /etc/avahi/services/:/external/avahi

      # avoid loops when mounting folders to /shares (I'd recommend explicit mapping for each share)
      - ${USER_1_SHARE_PATH}:/shares/${USER_1_SHARE_NAME}
      - ${USER_2_SHARE_PATH}:/shares/${USER_2_SHARE_NAME}
      - ${SHARED_PATH}:/shares/${SHARED_NAME}
